-- =====================================================================
-- JoyWatch seed data - GENERATED by tools/build_seed.php from titles.csv
-- Do not edit by hand. Import AFTER 01_schema.sql.
-- 116 titles, 17 genres, 1 demo user.
-- =====================================================================
SET NAMES utf8mb4;

-- Genres
INSERT INTO genres (name) VALUES
  ('Action'),
  ('Adventure'),
  ('Animation'),
  ('Comedy'),
  ('Crime'),
  ('Documentary'),
  ('Drama'),
  ('Family'),
  ('Fantasy'),
  ('History'),
  ('Horror'),
  ('Music'),
  ('Mystery'),
  ('Romance'),
  ('Science Fiction'),
  ('Thriller'),
  ('War');

-- Titles (the catalog)
INSERT INTO titles (media_type, tmdb_id, title, year, runtime, overview) VALUES
  ('movie', 278, 'The Shawshank Redemption', 1994, 142, 'A banker sentenced to life in prison forms an unlikely friendship and quietly holds on to hope.'),
  ('movie', 238, 'The Godfather', 1972, 175, 'The aging head of a crime family hands control of his empire to his reluctant youngest son.'),
  ('movie', 155, 'The Dark Knight', 2008, 152, 'Batman faces the Joker, a criminal who wants to prove that anyone can be pushed into chaos.'),
  ('movie', 680, 'Pulp Fiction', 1994, 154, 'Hitmen, a boxer, and a pair of diner robbers cross paths in interlocking Los Angeles stories.'),
  ('movie', 13, 'Forrest Gump', 1994, 142, 'A kind-hearted man drifts through decades of American history while never forgetting his first love.'),
  ('movie', 603, 'The Matrix', 1999, 136, 'A hacker learns that his everyday world is a simulation and joins a rebellion against the machines.'),
  ('movie', 27205, 'Inception', 2010, 148, 'A thief who steals secrets from dreams is hired to plant an idea instead.'),
  ('movie', 157336, 'Interstellar', 2014, 169, 'Explorers travel through a wormhole to find a new home for humanity as Earth fails.'),
  ('movie', 120, 'The Lord of the Rings: The Fellowship of the Ring', 2001, 179, 'A humble hobbit sets out with eight companions to destroy a dangerous ring.'),
  ('movie', 11, 'Star Wars', 1977, 121, 'A farm boy joins a rebel princess, a smuggler, and an old Jedi to fight a galactic empire.'),
  ('movie', 105, 'Back to the Future', 1985, 116, 'A teenager accidentally travels to 1955 and must make sure his parents fall in love.'),
  ('movie', 597, 'Titanic', 1997, 194, 'Two young people from different worlds fall in love aboard a doomed ocean liner.'),
  ('movie', 862, 'Toy Story', 1995, 81, 'A cowboy doll feels threatened when a flashy new space-ranger toy becomes the favorite.'),
  ('movie', 12, 'Finding Nemo', 2003, 100, 'An anxious clownfish crosses the ocean to rescue his son.'),
  ('movie', 129, 'Spirited Away', 2001, 125, 'A girl trapped in a world of spirits works at a bathhouse to free herself and her parents.'),
  ('movie', 150540, 'Inside Out', 2015, 95, 'The emotions inside a young girl''s head struggle to guide her through a big move.'),
  ('movie', 354912, 'Coco', 2017, 105, 'A boy who dreams of music journeys into the Land of the Dead to uncover his family history.'),
  ('movie', 324857, 'Spider-Man: Into the Spider-Verse', 2018, 117, 'Teen Miles Morales becomes Spider-Man and meets other Spider-People from parallel worlds.'),
  ('movie', 569094, 'Spider-Man: Across the Spider-Verse', 2023, 140, 'Miles is swept across the multiverse and clashes with a society of Spider-People.'),
  ('movie', 496243, 'Parasite', 2019, 133, 'A struggling family schemes its way into jobs with a wealthy household, with shocking results.'),
  ('movie', 545611, 'Everything Everywhere All at Once', 2022, 139, 'An overwhelmed laundromat owner must connect with versions of herself across the multiverse.'),
  ('movie', 438631, 'Dune', 2021, 155, 'A noble family takes control of a desert planet that holds the most valuable resource in the universe.'),
  ('movie', 693134, 'Dune: Part Two', 2024, 167, 'Paul Atreides unites with the Fremen while seeking revenge against those who destroyed his family.'),
  ('movie', 872585, 'Oppenheimer', 2023, 181, 'The story of the physicist who led the project to build the first atomic bomb.'),
  ('movie', 346698, 'Barbie', 2023, 114, 'Barbie leaves her perfect plastic world and discovers the complicated real world.'),
  ('movie', 299534, 'Avengers: Endgame', 2019, 181, 'The surviving Avengers attempt one last plan to undo a devastating loss.'),
  ('movie', 24428, 'The Avengers', 2012, 143, 'Earth''s mightiest heroes must learn to work together to stop an alien invasion.'),
  ('movie', 424, 'Schindler''s List', 1993, 195, 'A German businessman saves more than a thousand Jewish refugees during the Holocaust.'),
  ('movie', 19995, 'Avatar', 2009, 162, 'A paralyzed marine on an alien moon is torn between his orders and the people he comes to love.'),
  ('movie', 329, 'Jurassic Park', 1993, 127, 'A theme park of cloned dinosaurs goes terribly wrong during a preview tour.'),
  ('movie', 578, 'Jaws', 1975, 124, 'A police chief, a scientist, and a sailor hunt a giant shark terrorizing a beach town.'),
  ('movie', 694, 'The Shining', 1980, 144, 'A writer''s family spends the winter caretaking an isolated hotel that slowly drives him mad.'),
  ('movie', 419430, 'Get Out', 2017, 104, 'A young man''s visit to his girlfriend''s family turns into something deeply sinister.'),
  ('movie', 447332, 'A Quiet Place', 2018, 91, 'A family must live in silence to hide from creatures that hunt by sound.'),
  ('movie', 274, 'The Silence of the Lambs', 1991, 119, 'An FBI trainee seeks help from an imprisoned killer to catch another murderer.'),
  ('movie', 807, 'Se7en', 1995, 127, 'Two detectives track a killer whose crimes are based on the seven deadly sins.'),
  ('movie', 194, 'Amélie', 2001, 122, 'A shy Parisian waitress secretly improves the lives of the people around her.'),
  ('movie', 313369, 'La La Land', 2016, 129, 'A jazz pianist and an aspiring actress fall in love while chasing their dreams in Los Angeles.'),
  ('movie', 4348, 'Pride & Prejudice', 2005, 129, 'Elizabeth Bennet and the proud Mr. Darcy clash before discovering their feelings.'),
  ('movie', 9377, 'Ferris Bueller''s Day Off', 1986, 103, 'A charming high schooler skips school for an unforgettable day in Chicago.'),
  ('movie', 8363, 'Superbad', 2007, 113, 'Two awkward best friends try to make one wild party count before graduation.'),
  ('movie', 120467, 'The Grand Budapest Hotel', 2014, 100, 'A legendary hotel concierge and his lobby boy are pulled into a stolen-painting caper.'),
  ('movie', 115, 'The Big Lebowski', 1998, 117, 'A laid-back bowler is mistaken for a millionaire and dragged into a kidnapping plot.'),
  ('movie', 546554, 'Knives Out', 2019, 131, 'A detective investigates the death of a wealthy novelist surrounded by suspicious relatives.'),
  ('movie', 76341, 'Mad Max: Fury Road', 2015, 121, 'A drifter and a rebel warrior race across the desert to escape a tyrant.'),
  ('movie', 245891, 'John Wick', 2014, 101, 'A retired hitman returns to the underworld after gangsters take everything from him.'),
  ('movie', 361743, 'Top Gun: Maverick', 2022, 131, 'A veteran pilot trains young aviators for a nearly impossible mission.'),
  ('movie', 98, 'Gladiator', 2000, 155, 'A betrayed Roman general fights his way through the arena to seek justice.'),
  ('movie', 671, 'Harry Potter and the Philosopher''s Stone', 2001, 152, 'An orphan discovers he is a wizard and begins his first year at Hogwarts.'),
  ('movie', 109445, 'Frozen', 2013, 102, 'A fearless princess sets out to find her sister, whose icy powers have trapped their kingdom in winter.'),
  ('movie', 585, 'Monsters, Inc.', 2001, 92, 'Two monsters who scare children for a living have their world turned upside down by a little girl.'),
  ('movie', 10681, 'WALL·E', 2008, 98, 'A lonely trash-collecting robot falls in love and follows her into space.'),
  ('movie', 508947, 'Turning Red', 2022, 100, 'A confident 13-year-old turns into a giant red panda whenever she gets too excited.'),
  ('movie', 14160, 'Up', 2009, 96, 'A grumpy widower flies his house to South America, with a stowaway scout aboard.'),
  ('movie', 508442, 'Soul', 2020, 101, 'A music teacher''s soul gets separated from his body just before his big break.'),
  ('movie', 8587, 'The Lion King', 1994, 89, 'A young lion prince must reclaim his place after his father''s death.'),
  ('movie', 10020, 'Beauty and the Beast', 1991, 84, 'A bookish young woman is held in a castle by a cursed prince.'),
  ('movie', 2493, 'The Princess Bride', 1987, 98, 'A farmhand turned pirate fights to rescue his true love in a storybook adventure.'),
  ('movie', 1124, 'The Prestige', 2006, 130, 'Two rival magicians become obsessed with creating the ultimate illusion.'),
  ('movie', 210577, 'Gone Girl', 2014, 149, 'When his wife disappears, a husband becomes the prime suspect in a media frenzy.'),
  ('movie', 77338, 'The Intouchables', 2011, 113, 'A wealthy quadriplegic and his unlikely caregiver form a life-changing friendship.'),
  ('movie', 637, 'Life Is Beautiful', 1997, 116, 'A father uses humor to protect his son from the horrors of a concentration camp.'),
  ('movie', 372058, 'Your Name.', 2016, 106, 'Two teenagers in different parts of Japan mysteriously begin swapping bodies.'),
  ('movie', 4935, 'Howl''s Moving Castle', 2004, 119, 'A young woman cursed into old age finds refuge in a wizard''s walking castle.'),
  ('movie', 391713, 'Lady Bird', 2017, 94, 'A strong-willed teenager navigates her final year of high school and her relationship with her mother.'),
  ('movie', 530915, '1917', 2019, 119, 'Two young soldiers race across enemy territory to deliver a message that could save 1,600 lives.'),
  ('movie', 1422, 'The Departed', 2006, 151, 'An undercover cop and a mole in the police race to expose each other in Boston.'),
  ('movie', 264660, 'Ex Machina', 2015, 108, 'A programmer is invited to test whether a humanlike robot is truly conscious.'),
  ('movie', 286217, 'The Martian', 2015, 141, 'An astronaut stranded on Mars uses science and humor to survive until rescue.'),
  ('movie', 329865, 'Arrival', 2016, 116, 'A linguist is recruited to communicate with mysterious visitors from space.'),
  ('movie', 244786, 'Whiplash', 2014, 107, 'A young drummer is pushed to his limits by a ruthless music instructor.'),
  ('movie', 37799, 'The Social Network', 2010, 120, 'The founding of Facebook sparks lawsuits and broken friendships.'),
  ('movie', 381284, 'Hidden Figures', 2016, 127, 'Three Black women mathematicians at NASA help launch the space race.'),
  ('movie', 331482, 'Little Women', 2019, 135, 'Four sisters come of age in Civil War-era Massachusetts, each on her own path.'),
  ('movie', 346648, 'Paddington 2', 2017, 104, 'A polite bear is framed for stealing a pop-up book and lands in prison.'),
  ('movie', 10625, 'Mean Girls', 2004, 97, 'A new student is pulled into the social politics of a powerful high school clique.'),
  ('movie', 8835, 'Legally Blonde', 2001, 96, 'A fashion-loving sorority president follows her ex to Harvard Law and surprises everyone.'),
  ('movie', 11036, 'The Notebook', 2004, 123, 'An elderly man reads a love story from a faded notebook to a woman in a care home.'),
  ('movie', 9603, 'Clueless', 1995, 97, 'A popular Beverly Hills teen plays matchmaker and learns a few lessons of her own.'),
  ('movie', 515042, 'Free Solo', 2018, 100, 'Climber Alex Honnold attempts to scale El Capitan without ropes.'),
  ('movie', 682110, 'My Octopus Teacher', 2020, 85, 'A filmmaker forms an extraordinary bond with an octopus in a South African kelp forest.'),
  ('tv', 1396, 'Breaking Bad', 2008, 47, 'A chemistry teacher with a terminal diagnosis turns to making meth to secure his family''s future.'),
  ('tv', 60059, 'Better Call Saul', 2015, 48, 'A small-time lawyer slowly transforms into the morally flexible Saul Goodman.'),
  ('tv', 1399, 'Game of Thrones', 2011, 60, 'Noble families fight for control of the Iron Throne while an ancient threat returns.'),
  ('tv', 66732, 'Stranger Things', 2016, 55, 'Kids in a small Indiana town uncover secret experiments and a terrifying other world.'),
  ('tv', 1668, 'Friends', 1994, 22, 'Six friends navigate life, love, and careers in New York City.'),
  ('tv', 2316, 'The Office', 2005, 22, 'A mockumentary about the daily lives of employees at a paper company.'),
  ('tv', 8592, 'Parks and Recreation', 2009, 22, 'An optimistic parks department official tries to improve her small Indiana town.'),
  ('tv', 48891, 'Brooklyn Nine-Nine', 2013, 22, 'A talented but immature detective and his squad work under a strict new captain.'),
  ('tv', 66573, 'The Good Place', 2016, 25, 'A woman wakes up in the afterlife and realizes she was sent there by mistake.'),
  ('tv', 61662, 'Schitt''s Creek', 2015, 22, 'A wealthy family loses everything and must live in a tiny town they once bought as a joke.'),
  ('tv', 97546, 'Ted Lasso', 2020, 35, 'An American football coach with endless optimism is hired to manage an English soccer team.'),
  ('tv', 136315, 'The Bear', 2022, 30, 'A fine-dining chef returns home to run his family''s chaotic sandwich shop.'),
  ('tv', 100088, 'The Last of Us', 2023, 55, 'A hardened survivor escorts a teenage girl across a post-apocalyptic America.'),
  ('tv', 95396, 'Severance', 2022, 50, 'Office workers have their work memories surgically separated from their personal lives.'),
  ('tv', 76331, 'Succession', 2018, 60, 'The children of a media mogul fight for control of the family company.'),
  ('tv', 87108, 'Chernobyl', 2019, 65, 'A dramatization of the 1986 nuclear disaster and the people who tried to contain it.'),
  ('tv', 94605, 'Arcane', 2021, 40, 'Two sisters end up on opposite sides of a conflict between a wealthy city and its undercity.'),
  ('tv', 246, 'Avatar: The Last Airbender', 2005, 24, 'A young monk who can control all four elements must end a century-long war.'),
  ('tv', 82856, 'The Mandalorian', 2019, 38, 'A lone bounty hunter protects a mysterious child in the outer reaches of the galaxy.'),
  ('tv', 67070, 'Fleabag', 2016, 27, 'A witty, grieving woman navigates life and love in London while talking to the audience.'),
  ('tv', 65494, 'The Crown', 2016, 55, 'The reign of Queen Elizabeth II from her early years through modern times.'),
  ('tv', 91239, 'Bridgerton', 2020, 60, 'The eight siblings of a powerful family look for love in Regency-era London high society.'),
  ('tv', 93405, 'Squid Game', 2021, 55, 'Hundreds of people in debt compete in deadly children''s games for a huge cash prize.'),
  ('tv', 119051, 'Wednesday', 2022, 50, 'Wednesday Addams investigates a string of murders at her new boarding school.'),
  ('tv', 125935, 'Abbott Elementary', 2021, 22, 'A group of dedicated teachers make the best of an underfunded Philadelphia public school.'),
  ('tv', 107113, 'Only Murders in the Building', 2021, 32, 'Three neighbors who love true-crime podcasts investigate a death in their building.'),
  ('tv', 61222, 'BoJack Horseman', 2014, 25, 'A washed-up sitcom horse tries to reclaim his fame and figure out his life.'),
  ('tv', 1418, 'The Big Bang Theory', 2007, 22, 'Brilliant but socially awkward physicists befriend their new neighbor.'),
  ('tv', 1100, 'How I Met Your Mother', 2005, 22, 'A father tells his kids the long story of how he met their mother.'),
  ('tv', 456, 'The Simpsons', 1989, 22, 'The misadventures of a working-class family in the town of Springfield.'),
  ('tv', 1416, 'Grey''s Anatomy', 2005, 43, 'Surgical interns and doctors balance life-or-death cases with their personal lives.'),
  ('tv', 71912, 'The Witcher', 2019, 60, 'A monster hunter''s destiny becomes tied to a powerful sorceress and a young princess.'),
  ('tv', 70523, 'Dark', 2017, 55, 'A child''s disappearance exposes secrets spanning four generations and time itself.'),
  ('tv', 19885, 'Sherlock', 2010, 88, 'A modern-day Sherlock Holmes solves baffling cases with Dr. John Watson.'),
  ('tv', 84958, 'Loki', 2021, 50, 'The god of mischief is arrested by a time-policing agency and must help repair the timeline.');

-- Which genres each title has
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'movie' AND t.title = 'The Shawshank Redemption' AND g.name IN ('Drama', 'Crime');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'movie' AND t.title = 'The Godfather' AND g.name IN ('Drama', 'Crime');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'movie' AND t.title = 'The Dark Knight' AND g.name IN ('Action', 'Crime', 'Drama', 'Thriller');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'movie' AND t.title = 'Pulp Fiction' AND g.name IN ('Crime', 'Thriller');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'movie' AND t.title = 'Forrest Gump' AND g.name IN ('Comedy', 'Drama', 'Romance');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'movie' AND t.title = 'The Matrix' AND g.name IN ('Action', 'Science Fiction');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'movie' AND t.title = 'Inception' AND g.name IN ('Action', 'Science Fiction', 'Adventure');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'movie' AND t.title = 'Interstellar' AND g.name IN ('Adventure', 'Drama', 'Science Fiction');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'movie' AND t.title = 'The Lord of the Rings: The Fellowship of the Ring' AND g.name IN ('Adventure', 'Fantasy', 'Action');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'movie' AND t.title = 'Star Wars' AND g.name IN ('Adventure', 'Action', 'Science Fiction');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'movie' AND t.title = 'Back to the Future' AND g.name IN ('Adventure', 'Comedy', 'Science Fiction');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'movie' AND t.title = 'Titanic' AND g.name IN ('Drama', 'Romance');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'movie' AND t.title = 'Toy Story' AND g.name IN ('Animation', 'Adventure', 'Family', 'Comedy');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'movie' AND t.title = 'Finding Nemo' AND g.name IN ('Animation', 'Family', 'Comedy');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'movie' AND t.title = 'Spirited Away' AND g.name IN ('Animation', 'Family', 'Fantasy');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'movie' AND t.title = 'Inside Out' AND g.name IN ('Animation', 'Family', 'Comedy', 'Drama');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'movie' AND t.title = 'Coco' AND g.name IN ('Animation', 'Family', 'Fantasy', 'Music');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'movie' AND t.title = 'Spider-Man: Into the Spider-Verse' AND g.name IN ('Animation', 'Action', 'Adventure', 'Science Fiction');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'movie' AND t.title = 'Spider-Man: Across the Spider-Verse' AND g.name IN ('Animation', 'Action', 'Adventure', 'Science Fiction');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'movie' AND t.title = 'Parasite' AND g.name IN ('Comedy', 'Thriller', 'Drama');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'movie' AND t.title = 'Everything Everywhere All at Once' AND g.name IN ('Action', 'Adventure', 'Science Fiction', 'Comedy');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'movie' AND t.title = 'Dune' AND g.name IN ('Science Fiction', 'Adventure');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'movie' AND t.title = 'Dune: Part Two' AND g.name IN ('Science Fiction', 'Adventure');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'movie' AND t.title = 'Oppenheimer' AND g.name IN ('Drama', 'History');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'movie' AND t.title = 'Barbie' AND g.name IN ('Comedy', 'Adventure', 'Fantasy');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'movie' AND t.title = 'Avengers: Endgame' AND g.name IN ('Adventure', 'Science Fiction', 'Action');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'movie' AND t.title = 'The Avengers' AND g.name IN ('Science Fiction', 'Action', 'Adventure');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'movie' AND t.title = 'Schindler''s List' AND g.name IN ('Drama', 'History', 'War');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'movie' AND t.title = 'Avatar' AND g.name IN ('Action', 'Adventure', 'Fantasy', 'Science Fiction');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'movie' AND t.title = 'Jurassic Park' AND g.name IN ('Adventure', 'Science Fiction');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'movie' AND t.title = 'Jaws' AND g.name IN ('Horror', 'Thriller', 'Adventure');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'movie' AND t.title = 'The Shining' AND g.name IN ('Horror', 'Thriller');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'movie' AND t.title = 'Get Out' AND g.name IN ('Mystery', 'Thriller', 'Horror');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'movie' AND t.title = 'A Quiet Place' AND g.name IN ('Horror', 'Drama', 'Science Fiction');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'movie' AND t.title = 'The Silence of the Lambs' AND g.name IN ('Crime', 'Drama', 'Thriller');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'movie' AND t.title = 'Se7en' AND g.name IN ('Crime', 'Mystery', 'Thriller');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'movie' AND t.title = 'Amélie' AND g.name IN ('Comedy', 'Romance');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'movie' AND t.title = 'La La Land' AND g.name IN ('Comedy', 'Drama', 'Romance', 'Music');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'movie' AND t.title = 'Pride & Prejudice' AND g.name IN ('Drama', 'Romance');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'movie' AND t.title = 'Ferris Bueller''s Day Off' AND g.name IN ('Comedy');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'movie' AND t.title = 'Superbad' AND g.name IN ('Comedy');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'movie' AND t.title = 'The Grand Budapest Hotel' AND g.name IN ('Comedy', 'Drama');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'movie' AND t.title = 'The Big Lebowski' AND g.name IN ('Comedy', 'Crime');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'movie' AND t.title = 'Knives Out' AND g.name IN ('Comedy', 'Crime', 'Mystery');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'movie' AND t.title = 'Mad Max: Fury Road' AND g.name IN ('Action', 'Adventure', 'Science Fiction');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'movie' AND t.title = 'John Wick' AND g.name IN ('Action', 'Thriller');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'movie' AND t.title = 'Top Gun: Maverick' AND g.name IN ('Action', 'Drama');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'movie' AND t.title = 'Gladiator' AND g.name IN ('Action', 'Drama', 'Adventure');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'movie' AND t.title = 'Harry Potter and the Philosopher''s Stone' AND g.name IN ('Adventure', 'Fantasy', 'Family');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'movie' AND t.title = 'Frozen' AND g.name IN ('Animation', 'Family', 'Adventure', 'Fantasy');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'movie' AND t.title = 'Monsters, Inc.' AND g.name IN ('Animation', 'Comedy', 'Family');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'movie' AND t.title = 'WALL·E' AND g.name IN ('Animation', 'Family', 'Science Fiction');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'movie' AND t.title = 'Turning Red' AND g.name IN ('Animation', 'Family', 'Comedy', 'Fantasy');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'movie' AND t.title = 'Up' AND g.name IN ('Animation', 'Comedy', 'Family', 'Adventure');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'movie' AND t.title = 'Soul' AND g.name IN ('Animation', 'Family', 'Comedy', 'Fantasy');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'movie' AND t.title = 'The Lion King' AND g.name IN ('Animation', 'Family', 'Drama');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'movie' AND t.title = 'Beauty and the Beast' AND g.name IN ('Animation', 'Family', 'Fantasy', 'Romance', 'Music');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'movie' AND t.title = 'The Princess Bride' AND g.name IN ('Adventure', 'Family', 'Fantasy', 'Comedy', 'Romance');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'movie' AND t.title = 'The Prestige' AND g.name IN ('Drama', 'Mystery', 'Science Fiction');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'movie' AND t.title = 'Gone Girl' AND g.name IN ('Mystery', 'Thriller', 'Drama');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'movie' AND t.title = 'The Intouchables' AND g.name IN ('Drama', 'Comedy');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'movie' AND t.title = 'Life Is Beautiful' AND g.name IN ('Comedy', 'Drama');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'movie' AND t.title = 'Your Name.' AND g.name IN ('Animation', 'Romance', 'Drama');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'movie' AND t.title = 'Howl''s Moving Castle' AND g.name IN ('Animation', 'Fantasy', 'Adventure');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'movie' AND t.title = 'Lady Bird' AND g.name IN ('Comedy', 'Drama');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'movie' AND t.title = '1917' AND g.name IN ('War', 'Drama', 'History');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'movie' AND t.title = 'The Departed' AND g.name IN ('Drama', 'Thriller', 'Crime');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'movie' AND t.title = 'Ex Machina' AND g.name IN ('Drama', 'Science Fiction');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'movie' AND t.title = 'The Martian' AND g.name IN ('Drama', 'Adventure', 'Science Fiction');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'movie' AND t.title = 'Arrival' AND g.name IN ('Drama', 'Science Fiction', 'Mystery');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'movie' AND t.title = 'Whiplash' AND g.name IN ('Drama', 'Music');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'movie' AND t.title = 'The Social Network' AND g.name IN ('Drama');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'movie' AND t.title = 'Hidden Figures' AND g.name IN ('Drama', 'History');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'movie' AND t.title = 'Little Women' AND g.name IN ('Drama', 'Romance');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'movie' AND t.title = 'Paddington 2' AND g.name IN ('Adventure', 'Comedy', 'Family');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'movie' AND t.title = 'Mean Girls' AND g.name IN ('Comedy');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'movie' AND t.title = 'Legally Blonde' AND g.name IN ('Comedy', 'Romance');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'movie' AND t.title = 'The Notebook' AND g.name IN ('Romance', 'Drama');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'movie' AND t.title = 'Clueless' AND g.name IN ('Comedy', 'Romance');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'movie' AND t.title = 'Free Solo' AND g.name IN ('Documentary');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'movie' AND t.title = 'My Octopus Teacher' AND g.name IN ('Documentary');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'tv' AND t.title = 'Breaking Bad' AND g.name IN ('Drama', 'Crime', 'Thriller');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'tv' AND t.title = 'Better Call Saul' AND g.name IN ('Crime', 'Drama');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'tv' AND t.title = 'Game of Thrones' AND g.name IN ('Fantasy', 'Drama', 'Adventure', 'Action');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'tv' AND t.title = 'Stranger Things' AND g.name IN ('Drama', 'Fantasy', 'Science Fiction', 'Mystery', 'Horror');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'tv' AND t.title = 'Friends' AND g.name IN ('Comedy', 'Romance');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'tv' AND t.title = 'The Office' AND g.name IN ('Comedy');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'tv' AND t.title = 'Parks and Recreation' AND g.name IN ('Comedy');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'tv' AND t.title = 'Brooklyn Nine-Nine' AND g.name IN ('Comedy', 'Crime');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'tv' AND t.title = 'The Good Place' AND g.name IN ('Comedy', 'Fantasy');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'tv' AND t.title = 'Schitt''s Creek' AND g.name IN ('Comedy');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'tv' AND t.title = 'Ted Lasso' AND g.name IN ('Comedy', 'Drama');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'tv' AND t.title = 'The Bear' AND g.name IN ('Comedy', 'Drama');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'tv' AND t.title = 'The Last of Us' AND g.name IN ('Drama', 'Action', 'Adventure', 'Science Fiction', 'Horror');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'tv' AND t.title = 'Severance' AND g.name IN ('Drama', 'Mystery', 'Science Fiction', 'Thriller');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'tv' AND t.title = 'Succession' AND g.name IN ('Drama', 'Comedy');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'tv' AND t.title = 'Chernobyl' AND g.name IN ('Drama', 'History');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'tv' AND t.title = 'Arcane' AND g.name IN ('Animation', 'Action', 'Adventure', 'Fantasy', 'Science Fiction', 'Drama');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'tv' AND t.title = 'Avatar: The Last Airbender' AND g.name IN ('Animation', 'Action', 'Adventure', 'Fantasy', 'Family', 'Comedy');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'tv' AND t.title = 'The Mandalorian' AND g.name IN ('Science Fiction', 'Action', 'Adventure', 'Drama');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'tv' AND t.title = 'Fleabag' AND g.name IN ('Comedy', 'Drama');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'tv' AND t.title = 'The Crown' AND g.name IN ('Drama', 'History');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'tv' AND t.title = 'Bridgerton' AND g.name IN ('Drama', 'Romance');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'tv' AND t.title = 'Squid Game' AND g.name IN ('Action', 'Mystery', 'Drama', 'Thriller');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'tv' AND t.title = 'Wednesday' AND g.name IN ('Comedy', 'Mystery', 'Fantasy', 'Horror');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'tv' AND t.title = 'Abbott Elementary' AND g.name IN ('Comedy');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'tv' AND t.title = 'Only Murders in the Building' AND g.name IN ('Comedy', 'Mystery', 'Crime');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'tv' AND t.title = 'BoJack Horseman' AND g.name IN ('Animation', 'Comedy', 'Drama');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'tv' AND t.title = 'The Big Bang Theory' AND g.name IN ('Comedy', 'Romance');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'tv' AND t.title = 'How I Met Your Mother' AND g.name IN ('Comedy', 'Romance');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'tv' AND t.title = 'The Simpsons' AND g.name IN ('Animation', 'Comedy', 'Family');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'tv' AND t.title = 'Grey''s Anatomy' AND g.name IN ('Drama', 'Romance');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'tv' AND t.title = 'The Witcher' AND g.name IN ('Drama', 'Fantasy', 'Action', 'Adventure');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'tv' AND t.title = 'Dark' AND g.name IN ('Crime', 'Drama', 'Mystery', 'Science Fiction', 'Thriller');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'tv' AND t.title = 'Sherlock' AND g.name IN ('Crime', 'Drama', 'Mystery');
INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = 'tv' AND t.title = 'Loki' AND g.name IN ('Drama', 'Science Fiction', 'Fantasy', 'Adventure');

-- Demo user (username: demo / password: joywatch)
INSERT INTO users (username, display_name, password_hash) VALUES ('demo', 'Demo Viewer', '$2y$12$1B/M5uZUj0Kcpvv6MJTySOKuD/SGmkb3hrwknIcg/Oir6/LUL9Qie');
SET @demo = (SELECT id FROM users WHERE username = 'demo');
INSERT INTO user_titles (user_id, title_id, watch_status, interest, rating, rewatch, notes, date_rated) SELECT @demo, id, 'watched', NULL, 2, 'yes', 'Still thinking about the ending.', NOW() FROM titles WHERE media_type = 'movie' AND title = 'Inception';
INSERT INTO user_titles (user_id, title_id, watch_status, interest, rating, rewatch, notes, date_rated) SELECT @demo, id, 'watched', NULL, 1, 'maybe', NULL, NOW() FROM titles WHERE media_type = 'movie' AND title = 'Toy Story';
INSERT INTO user_titles (user_id, title_id, watch_status, interest, rating, rewatch, notes, date_rated) SELECT @demo, id, 'watched', NULL, 2, 'yes', NULL, NOW() FROM titles WHERE media_type = 'movie' AND title = 'Coco';
INSERT INTO user_titles (user_id, title_id, watch_status, interest, rating, rewatch, notes, date_rated) SELECT @demo, id, 'watched', NULL, -2, 'no', 'Too scary for me.', NOW() FROM titles WHERE media_type = 'movie' AND title = 'The Shining';
INSERT INTO user_titles (user_id, title_id, watch_status, interest, rating, rewatch, notes, date_rated) SELECT @demo, id, 'watched', NULL, 1, 'yes', NULL, NOW() FROM titles WHERE media_type = 'movie' AND title = 'Knives Out';
INSERT INTO user_titles (user_id, title_id, watch_status, interest, rating, rewatch, notes, date_rated) SELECT @demo, id, 'watched', NULL, 0, 'maybe', NULL, NOW() FROM titles WHERE media_type = 'movie' AND title = 'Barbie';
INSERT INTO user_titles (user_id, title_id, watch_status, interest, rating, rewatch, notes, date_rated) SELECT @demo, id, 'not_yet', 'yes', NULL, NULL, 'Watch on the big TV.', NULL FROM titles WHERE media_type = 'movie' AND title = 'Dune: Part Two';
INSERT INTO user_titles (user_id, title_id, watch_status, interest, rating, rewatch, notes, date_rated) SELECT @demo, id, 'not_yet', 'yes', NULL, NULL, NULL, NULL FROM titles WHERE media_type = 'movie' AND title = 'Paddington 2';
INSERT INTO user_titles (user_id, title_id, watch_status, interest, rating, rewatch, notes, date_rated) SELECT @demo, id, 'not_yet', 'unsure', NULL, NULL, NULL, NULL FROM titles WHERE media_type = 'movie' AND title = 'Get Out';
INSERT INTO user_titles (user_id, title_id, watch_status, interest, rating, rewatch, notes, date_rated) SELECT @demo, id, 'not_yet', 'not_interested', NULL, NULL, NULL, NULL FROM titles WHERE media_type = 'movie' AND title = 'John Wick';
INSERT INTO user_titles (user_id, title_id, watch_status, interest, rating, rewatch, notes, date_rated) SELECT @demo, id, 'watching', NULL, 2, NULL, NULL, NOW() FROM titles WHERE media_type = 'tv' AND title = 'Ted Lasso';
INSERT INTO user_titles (user_id, title_id, watch_status, interest, rating, rewatch, notes, date_rated) SELECT @demo, id, 'watching', NULL, NULL, NULL, NULL, NULL FROM titles WHERE media_type = 'tv' AND title = 'The Bear';
INSERT INTO user_titles (user_id, title_id, watch_status, interest, rating, rewatch, notes, date_rated) SELECT @demo, id, 'not_yet', 'yes', NULL, NULL, NULL, NULL FROM titles WHERE media_type = 'tv' AND title = 'Only Murders in the Building';
UPDATE user_titles SET own_bluray = 1 WHERE user_id = @demo AND title_id = (SELECT id FROM titles WHERE title = 'Inception');
UPDATE user_titles SET own_dvd = 1, own_digital = 1 WHERE user_id = @demo AND title_id = (SELECT id FROM titles WHERE title = 'Toy Story');
INSERT INTO user_genre_prefs (user_id, genre_id, rating) SELECT @demo, id, 2 FROM genres WHERE name IN ('Animation', 'Comedy');
INSERT INTO user_genre_prefs (user_id, genre_id, rating) SELECT @demo, id, -2 FROM genres WHERE name = 'Horror';
