<?php
/**
 * Builds database/02_seed.sql from database/titles.csv.
 *
 * WHY: titles.csv is easy to edit in Google Sheets. After editing it,
 * download it as CSV, replace database/titles.csv, then run:
 *
 *     php tools/build_seed.php
 *
 * and re-import database/02_seed.sql in phpMyAdmin.
 *
 * This script is a developer tool. It is NOT uploaded to Keymaker.
 */

$root    = dirname(__DIR__);
$csvPath = $root . '/database/titles.csv';
$outPath = $root . '/database/02_seed.sql';

$fh = fopen($csvPath, 'r');
if (!$fh) {
    fwrite(STDERR, "Cannot open $csvPath\n");
    exit(1);
}

$header = fgetcsv($fh, 0, ',', '"', '');
$expected = ['media_type', 'tmdb_id', 'title', 'year', 'runtime', 'genres', 'overview'];
if ($header !== $expected) {
    fwrite(STDERR, "titles.csv header must be: " . implode(',', $expected) . "\n");
    exit(1);
}

function q($value) {
    if ($value === null || $value === '') {
        return 'NULL';
    }
    return "'" . str_replace(["\\", "'"], ["\\\\", "''"], $value) . "'";
}

$rows      = [];
$allGenres = [];
$seen      = [];
$line      = 1;
while (($r = fgetcsv($fh, 0, ',', '"', '')) !== false) {
    $line++;
    if (count($r) === 1 && trim($r[0]) === '') {
        continue; // blank line
    }
    $row = array_combine($expected, array_map('trim', $r));
    if (!in_array($row['media_type'], ['movie', 'tv'], true) || $row['title'] === '') {
        fwrite(STDERR, "Skipping line $line: needs media_type movie/tv and a title\n");
        continue;
    }
    // Canonical identity = media_type + tmdb_id (or title + year when no tmdb_id)
    $key = $row['media_type'] . ':' . ($row['tmdb_id'] !== '' ? $row['tmdb_id'] : strtolower($row['title']) . $row['year']);
    if (isset($seen[$key])) {
        fwrite(STDERR, "Skipping line $line: duplicate of {$seen[$key]}\n");
        continue;
    }
    $seen[$key] = "line $line";
    $row['genre_list'] = array_values(array_filter(array_map('trim', explode('|', $row['genres']))));
    foreach ($row['genre_list'] as $g) {
        $allGenres[$g] = true;
    }
    $rows[] = $row;
}
fclose($fh);
ksort($allGenres);

$out   = [];
$out[] = '-- =====================================================================';
$out[] = '-- JoyWatch seed data - GENERATED by tools/build_seed.php from titles.csv';
$out[] = '-- Do not edit by hand. Import AFTER 01_schema.sql.';
$out[] = '-- ' . count($rows) . ' titles, ' . count($allGenres) . ' genres, 1 demo user.';
$out[] = '-- =====================================================================';
$out[] = 'SET NAMES utf8mb4;';
$out[] = '';
$out[] = '-- Genres';
$out[] = 'INSERT INTO genres (name) VALUES';
$out[] = '  (' . implode("),\n  (", array_map('q', array_keys($allGenres))) . ');';
$out[] = '';
$out[] = '-- Titles (the catalog)';
$out[] = 'INSERT INTO titles (media_type, tmdb_id, title, year, runtime, overview) VALUES';
$values = [];
foreach ($rows as $row) {
    $values[] = sprintf(
        '  (%s, %s, %s, %s, %s, %s)',
        q($row['media_type']),
        $row['tmdb_id'] === '' ? 'NULL' : (int) $row['tmdb_id'],
        q($row['title']),
        $row['year'] === '' ? 'NULL' : (int) $row['year'],
        $row['runtime'] === '' ? 'NULL' : (int) $row['runtime'],
        q($row['overview'])
    );
}
$out[] = implode(",\n", $values) . ';';
$out[] = '';
$out[] = '-- Which genres each title has';
foreach ($rows as $row) {
    if (!$row['genre_list']) {
        continue;
    }
    $out[] = sprintf(
        'INSERT INTO title_genres (title_id, genre_id) SELECT t.id, g.id FROM titles t, genres g WHERE t.media_type = %s AND t.title = %s AND g.name IN (%s);',
        q($row['media_type']),
        q($row['title']),
        implode(', ', array_map('q', $row['genre_list']))
    );
}

// ---------------------------------------------------------------------
// Demo account so the professor (and we) can log in and see real data.
//   username: demo     password: joywatch
// ---------------------------------------------------------------------
$demoHash = password_hash('joywatch', PASSWORD_DEFAULT);
$out[] = '';
$out[] = '-- Demo user (username: demo / password: joywatch)';
$out[] = "INSERT INTO users (username, display_name, password_hash) VALUES ('demo', 'Demo Viewer', " . q($demoHash) . ');';
$out[] = "SET @demo = (SELECT id FROM users WHERE username = 'demo');";

// title => [watch_status, interest, rating, rewatch, notes]
$demo = [
    ['movie', 'Inception',                 'watched',  null,             2,    'yes',   'Still thinking about the ending.'],
    ['movie', 'Toy Story',                 'watched',  null,             1,    'maybe', null],
    ['movie', 'Coco',                      'watched',  null,             2,    'yes',   null],
    ['movie', 'The Shining',               'watched',  null,             -2,   'no',    'Too scary for me.'],
    ['movie', 'Knives Out',                'watched',  null,             1,    'yes',   null],
    ['movie', 'Barbie',                    'watched',  null,             0,    'maybe', null],
    ['movie', 'Dune: Part Two',            'not_yet',  'yes',            null, null,    'Watch on the big TV.'],
    ['movie', 'Paddington 2',              'not_yet',  'yes',            null, null,    null],
    ['movie', 'Get Out',                   'not_yet',  'unsure',         null, null,    null],
    ['movie', 'John Wick',                 'not_yet',  'not_interested', null, null,    null],
    ['tv',    'Ted Lasso',                 'watching', null,             2,    null,    null],
    ['tv',    'The Bear',                  'watching', null,             null, null,    null],
    ['tv',    'Only Murders in the Building', 'not_yet', 'yes',          null, null,    null],
];
foreach ($demo as $d) {
    list($type, $title, $status, $interest, $rating, $rewatch, $notes) = $d;
    $out[] = sprintf(
        'INSERT INTO user_titles (user_id, title_id, watch_status, interest, rating, rewatch, notes, date_rated) '
        . 'SELECT @demo, id, %s, %s, %s, %s, %s, %s FROM titles WHERE media_type = %s AND title = %s;',
        q($status),
        q($interest),
        $rating === null ? 'NULL' : (int) $rating,
        q($rewatch),
        q($notes),
        $rating === null ? 'NULL' : 'NOW()',
        q($type),
        q($title)
    );
}
$out[] = "UPDATE user_titles SET own_bluray = 1 WHERE user_id = @demo AND title_id = (SELECT id FROM titles WHERE title = 'Inception');";
$out[] = "UPDATE user_titles SET own_dvd = 1, own_digital = 1 WHERE user_id = @demo AND title_id = (SELECT id FROM titles WHERE title = 'Toy Story');";
$out[] = "INSERT INTO user_genre_prefs (user_id, genre_id, rating) SELECT @demo, id, 2 FROM genres WHERE name IN ('Animation', 'Comedy');";
$out[] = "INSERT INTO user_genre_prefs (user_id, genre_id, rating) SELECT @demo, id, -2 FROM genres WHERE name = 'Horror';";
$out[] = '';

file_put_contents($outPath, implode("\n", $out));
echo 'Wrote ' . $outPath . ' (' . count($rows) . " titles)\n";
